import type { Metadata } from "next";
import "./Styles/globals.css";
import { PortfolioProvider } from "./_context/PortfolioContext";
import Navigation from "./Components/Navigation";
import MenuPage from "./Components/MenuPage";
import { sourceSans } from "./fonts/fonts";

export const metadata: Metadata = {
  title: "Ifeanyi Iheme | Frontend Engineer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* bg-[#171c28]  */}

      <body className={`${sourceSans.className} bg-[#0f172a] text-[#e7e7e7] `}>
        <PortfolioProvider>
          <>
            <Navigation />
            <MenuPage />
            {children}
          </>
        </PortfolioProvider>
      </body>
    </html>
  );
}
